### ISSUE TITLE
HOWTO: connect to 2 or more Serial Ports at the same time

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [elixir-circuits/circuits_uart#158]
Please can we connect to 2 ore more Serial Ports at the same time?

Please can you give a small example if this is indeed possible.

Thanks!

**Comment by fhunleth** [comment]
Yes. Call `Circuits.UART.start_link` for each serial port that you want to use. Each serial port is a separate GenServer.

**Comment by CharlesOkwuagwu** [comment]
> Yes. Call `Circuits.UART.start_link` for each serial port that you want to use. Each serial port is a separate GenServer.

Works Perfectly!
Thanks!
