### ISSUE TITLE
Discussion: Move this to elixir-circuits umbrella?

### ISSUE THREAD

**Issue by jjcarstens** [elixir-circuits/circuits_uart#54]
With all the new [`elixir-circuits`](https://github.com/elixir-circuits) work going on for GPIO, I2c, and SPI, would it make sense to move `nerves_uart` to that umbrella instead as `circuits_uart`?

It seems to be a common misconception that one would need nerves to use this and moving might help separate the distinction from nerves.

But on the flip side, it might not be technically a “circuit” since UART is not dependent on pin headers and is focused on being cross platform library.

**Comment by fhunleth** [comment]
Yes, totally agree. Our plan is to move it. 

I was going to do it after we released `circuits_gpio`. You're the n'th person to ask me about this, though, so let me see if I can just get it done.

**Comment by jjcarstens** [comment]
I’d be happy to help and get it started if you can just create the repo in elixir circuits

**Comment by fhunleth** [comment]
That would be awesome! Several things just popped up at work and now I'm not sure if I can get to this today or tomorrow, but the first step is just renaming everything to `circuits_uart`. I assume that it's a simple search and replace, but I'm sure that there will be a few places that need extra scrutiny. If you want to take a pass at that in a fork, then I'll pull your fork when I set up the new repo and update the CI settings. That would save me quite a bit of time and probably get things most of the way there.

**Comment by fhunleth** [comment]
You're totally making my day! Thanks!

I really hope to get a chance to take the next pass tonight.

**Comment by fhunleth** [comment]
Here's where I'm at: https://github.com/elixir-circuits/circuits_uart

I think that it's really close. Unit tests pass and the docs look good at a glance. Need to button it up in a release and post about it - probably later this week.

**Comment by fhunleth** [comment]
Moved
