### ISSUE TITLE
Can't close connection to unopened device

### ISSUE THREAD

**Issue by ConnorRigby** [elixir-circuits/circuits_uart#75]
https://github.com/elixir-circuits/circuits_uart/blob/4832c8748edc488d6840a780c366c35d509f345d/lib/circuits_uart.ex#L511

This line will cause an exception if `UART.open/3` was not called, or if it was called, but returned an error

**Comment by fhunleth** [comment]
It looks like the line could be deleted anyway. Want to send a PR?
