### ISSUE TITLE
Issues with Fona 808 on Raspberry Pi Zero W

### ISSUE THREAD

**Issue by arduino-man** [elixir-circuits/circuits_uart#99]
## Setup

  - Version: Circuits UART 1.4.2
  - OS: Elixir 1.11.2  -  Nerves 1.7.5 
  - Platform: Raspberry Pi Zero W
  
## Expected Behavior
Talk to a Fona 808 device using Circuits UART on a Raspberry Pi Zero W.

## Actual Behavior
Cannot talk to Fona 808 when using a Raspberry Pi Zero W, the responses from the device are either empty or "Unknown Command" or a bunch of "\b\b\b\b\b\b\b\b\b\b\b" characters.

## Steps to Reproduce the Problem
I have a Fona 808 device which I am able to talk to via UART using a USB to TTL adapter and Circuits UART on my laptop with IEX but cannot do the same when using Circuits UART on a Raspberry Pi Zero W and Nerves.

SAMPLE OUTPUT:

iex(5)> Circuits.UART.read(pid, 1000)
{:ok, ""}

iex(5)> Circuits.UART.read(pid, 1000)
{:ok,
 "d\r --> > Unknown command\rUnknown command\r --> n command\rUnknown command\r"}

iex(5)> Circuits.UART.read(pid, 1000)
{:ok,
 {:partial,
  " \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b \b "}}

![20210425_092639](https://user-images.githubusercontent.com/5546597/115999449-019c2b00-a5a9-11eb-8f5c-e1b633b5e3e3.jpg)
![20210425_092653](https://user-images.githubusercontent.com/5546597/115999450-0234c180-a5a9-11eb-9983-a68141655278.jpg)

**Comment by fhunleth** [comment]
Can you confirm that the baud rate is set correctly?

**Comment by fhunleth** [comment]
My second idea is to add this to your config:

```
  config :nerves, :erlinit,
    ctty: "/dev/null"
```

I just realized that you're on a Pi Zero and the serial console should be running on the same UART. I.e., it's sending IEx prompts to the Fona 808 and that's probably not good at all.

**Comment by arduino-man** [comment]
I can confirm that the baud rate is set correctly (115200).
Is there anything I can do to prevent the issue with IEX commands being sent to the Fona via UART?  Thanks for your prompt response

**Comment by arduino-man** [comment]
Oh sorry, I just realized your suggestion was part of your comment, making that change now and will report right back

**Comment by arduino-man** [comment]
I added the new configuration line redirecting output to /dev/null but no success.

My config file can be seen here in case I did anything wrong.  https://pastebin.com/KLEPmEYD

**Comment by arduino-man** [comment]
I also found this forum entry where someone encountered what seems to be the exact same issue. The issue seems to have never been resolved unfortunately.  https://elixirforum.com/t/circuiits-uart-problems-in-rpi0/33710/7

**Comment by arduino-man** [comment]
Doing 

config :nerves, :erlinit, ctty: "ttyS0"

Seems to have resolved the issue or at least dramatically improved it. I will stress test and report back in an hour or so.   

Thanks!

**Comment by fhunleth** [comment]
Weird. Another thing to try is to turn off kernel messages being output over the UART. I'd manually try this out first by putting the MicroSD card in your computer and editing the `cmdline.txt` file. The line at the end says this:

```
root=/dev/mmcblk0p2 rootwait console=serial0,115200 quiet
```

Delete the console part so it's like this:

```
root=/dev/mmcblk0p2 rootwait quiet
```

**Comment by arduino-man** [comment]
Adding: 

config :nerves, :erlinit, ctty: "ttyS0"

completely fixed the issue! Thanks a lot for pointing me in the right direction.
